spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/backend?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  data:
    r2dbc:
      repositories:
        enabled: true

aws:
  s3:
    localEnabled: true
    multipartMinPartSize: 5242880
    numRetries: 2
    bucketName: wonho-bucket
    region: us-east-1
    localEndpoint: http://s3.localhost.localstack.cloud:4566
    accessKey: localstack
    secretKey: localstack
#    bucketName: babybook-file-bucket
#    region: ap-northeast-2
#    localEndpoint: https://babybook-file-bucket.s3.ap-northeast-2.amazonaws.com