spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/backend?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  data:
    r2dbc:
      repositories:
        enabled: true

aws:
  region: ap-northeast-2
  s3:
    bucket-name: backend