spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/backend?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  data:
    r2dbc:
      repositories:
        enabled: true

aws:
  s3:
    localEnabled: true
    localEndpoint: http://s3.localhost.localstack.cloud:4566
    region: us-east-1
    numRetries: 2
    bucketName: wonho-bucket
    multipartMinPartSize: 5242880

