services:
  localstack:
    container_name: aws-infra
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - DEFAULT_REGION="us-east-1"
      - S3_SKIP_SIGNATURE_VALIDATION=1       # 서명 오류 무시 (테스트용)
      - PERSISTENCE=0                        # 컨테이너 재시작 시 데이터 초기화
    volumes:
      - ./localstack:/etc/localstack/init/ready.d
      - ./localstack/data:/var/lib/localstack'
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    container_name: mono-redis
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
