[versions]
kotlin = "2.2.0"
kotest = "6.0.0"

[libraries]
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
